apiVersion: apps/v1
kind: Depolyment
metadata:
  name: myapp-ft
  labels:
    app: myapp
spec:
  replicas: 3
  sector:
    matchLabels: myapp
    app: myapp
  template: 
    metadata: 
    labels:
      app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:1.0
    ports:
    - containers: 3000
---
apiVersion: v1
kind: Service
metadata: 
  name: myapp-service
spec: 
  type: NodePort
  selector: 
    app: myapp
  ports:   
  - portocol: TCP
    port: 8080
    targetPort: 3000
